apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    app: demo
    lang: java
spec:
  volumes:
    - name: temp-volume
      emptyDir: { }
    - name: mvn-persistent-volume
      emptyDir: { }
  containers:
    - name: app-container
      image: docker.io/hackedlings/demo:1.0
      imagePullPolicy: Always
      volumeMounts:
        - name: temp-volume
          mountPath: /openshift/temp/
        - name: mvn-persistent-volume
          mountPath: /openshift/persistent/
      env:
        - name: TEMP_VOLUME
          value: /openshift/temp/
        - name: MVN_VOLUME
          mountPath: /openshift/persistent/
      envFrom:
        - secretRef:
            name: docker.io
      resources:
        limits:
          memory: 1Gi
          cpu: 1
        requests:
          memory: 1Gi
          cpu: 1
  restartPolicy: Never