apiVersion: v1
kind: Pod
metadata:
  labels:
    app: demo
    lang: java
    name: demo
spec:
  volumes:
    - name: shared-logs
      emptyDir: { }
  containers:
    - name: app-container
      image: hackedlings/demo:1.0
      imagePullPolicy: Always
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log
      resources:
        limits:
          memory: 0.5Gi
          cpu: 100m
        requests:
          memory: 0.2Gi
          cpu: 100m