apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.configmapname" . }}
  namespace: {{ .Values.global.namespace }}
data:
  TEST_SET: {{ .Values.configmap.testSet }}
  TEST_PLAN: {{ .Values.configmap.testPlan }}
  ACTIVE_PROFILES: {{ .Values.configmap.activeProfiles }}