apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    lang: java
spec:
  volumes:
    - name: temp-volume
      emptyDir: {}
    - name: mvn-persistent-volume
      emptyDir: {}
  containers:
    - name: app-container-{{ .Release.Name }}
      image: docker.io/hackedlings/demo:latest
      imagePullPolicy: Always
      volumeMounts:
        - name: temp-volume
          mountPath: /openshift/temp/
        - name: mvn-persistent-volume
          mountPath: /openshift/persistent/
      env:
        - name: TEMP_VOLUME
          value: /openshift/temp/
        - name: MVN_VOLUME
          value: /openshift/persistent/
      envFrom:
        - configMapRef:
            name: {{ .Release.Name }}_config_map
      resources:
        limits:
          memory: {{ .Values.spec.resources.limits.memory }}
          cpu: {{ .Values.spec.resources.limits.cpu }}
        requests:
          memory: {{ .Values.spec.resources.requests.memory }}
          cpu: {{ .Values.spec.resources.requests.cpu }}
  restartPolicy: Never
