apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.secretname" . }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  username: {{ .Values.secret.username | b64enc }}
