global:
  namespace: pks9862728888-dev
  hostname: apps.sandbox.x8i5.p1.openshiftapps.com
secret:
  username: dummyusername
  password: dummypassword
configmap:
  testSet: TESTSET-1234
  testPlan: TESTPLAN-1234
  activeProfiles: server
spec:
  imageName: docker.io/hackedlings/demo:2.0
  persistentVolume:
    enabled: false
    emptyDir: {}
    claimName: dummy-claim
  resources:
    limits:
      memory: 1Gi
      cpu: 1
    requests:
      memory: 1Gi
      cpu: 1