apiVersion: v1
kind: Pod
metadata:
  labels:
    app: demo
    lang: java
    name: demo
spec:
  volumes:
    - name: temp-volume
      emptyDir: { }
    - name: mvn-persistent-volume
      persistentVolumeClaim:
        claimName: mvn-persistent-volume
  containers:
    - name: app-container
      image: docker.io/hackedlings/demo:1.0
      imagePullPolicy: Always
      volumeMounts:
        - name: temp-volume
          mountPath: /openshift/temp/
        - name: mvn-persistent-volume
          mountPath: /openshift/persistent/
      env:
        - name: TEMP_VOLUME
          value: /openshift/temp/
        - name: MVN_VOLUME
          mountPath: /openshift/persistent/
      resources:
        limits:
          memory: 0.5Gi
          cpu: 100m
        requests:
          memory: 0.2Gi
          cpu: 100m