apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
  spec:
    containers:
      - name: demo
        image: docker.io/hackedlings/demo:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: temp-volume
            mountPath: /openshift/temp/
          - name: mvn-persistent-volume
            mountPath: /openshift/persistent/
        env:
          - name: TEMP_VOLUME
            value: /openshift/temp/
          - name: MVN_VOLUME
            value: /openshift/persistent/
    volumes:
      - name: temp-volume
        emptyDir: { }
      - name: mvn-persistent-volume
        emptyDir: { }
