apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cronjob
  namespace: {{ .Values.global.namespace }}
spec:
  schedule: "2 12 * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Release.Name }}
              image: {{ .Values.spec.imageName }}
              args:
                - /bin/bash
                - '-cx'
                - eval "curl {{ .Release.Name }}.{{ .Values.global.namespace }}.{{ .Values.global.hostname }}/prune-expired-artifacts"
          restartPolicy: OnFailure
