apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.ingressname" . }}
  namespace: {{ .Values.global.namespace }}
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Values.global.namespace }}.{{ .Values.global.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "chart.servicename" . }}
                port:
                  number: 80
