apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.secretname" . }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  NON_PRIVILEGED_USERS: {{ .Values.secret.nonPrivilegedUsers | b64enc }}
  ADMIN_USER: {{ .Values.secret.adminUser | b64enc }}
  NON_PRIVILEGED_USER_PASSWORD: {{ .Values.secret.nonPrivilegedUserPassword | b64enc }}
  ADMIN_USER_PASSWORD: {{ .Values.secret.adminUserPassword | b64enc }}
