apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.servicename" . }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
